### PR TITLE
Minor cleanup: rename and add changelog

### PR DESCRIPTION
**Pull request by sirosen**
- Rename 'reusable-workflows' to 'workflows'
- Introduce a changelog file

---

This is a pair of very minor changes to try to put this repo on good footing, regardless of its content.

### CODE REVIEW

**Comment by kurtmckee** [comment]
I'm not onboard for calling this branch `v1`. Current common practice is to use a moving git tag.

**Comment by sirosen** [comment]
I replaced `v1` with `main` in the repo. But I think `v1` should be a branch, not a tag (?). It feels weird to me to be moving a tag when you could just use a branch for that purpose.
I'm retargeting this to `main`. Can we refine the changelog contents later? I just want it to exist at all, as a first step.

**Review by kurtmckee — APPROVED** [review]
> It feels weird

Don't let it!

> you could just use a branch

I don't recommend breaking with current common practice; using a branch has only the potential to harm tool support (for example, how pre-commit documents that it will always refuse to update its cache if you use a branch name instead of a tag to identify the hook version). I anticipate Dependabot could have problems if we don't follow established GitHub action versioning practices.

**Comment by sirosen** [comment]
I think you raise a reasonable concern RE tool support. 

I stand by my gut reaction that this moving around of tags is at odds with git itself -- which has limited provisions for doing this -- but I'll try to ignore that for the most part.

**Pull request merged**
